# Author: Bryan Sazon <john.bryan.j.sazon@accenture.com>

version: '2'

networks:
  &network wlsnet:
    driver: bridge

services:

  # Deploys the AdminServer
  adminserver:
    container_name: adminserver
    image: 1221-app-jms-domain
    restart: always
    environment:
      DS_NAME: "Oracle"
      DS_DB_TYPE: "Oracle"
      DS_DB_NAME: "dockerdb"
      DS_JNDI_NAME: "jdbc/oracleDatabase"
      DS_JDBC_DRIVER: "oracle.jdbc.driver.OracleDriver"
      DS_JDBC_URL: "jdbc:oracle:thin:system/password123@oracledb:1521:XE"
      DS_DB_HOST: "oracledb"
      DS_DB_PORT: "1521"
      DS_DB_USER: "system"
      DS_DB_PASSWORD: "password123"
    ports:
      - "8001:8001"
    networks:
      - *network

  # Deploys the Database Service
  database:
    container_name: oracledb
    image: oracle/database:11.2.0.2-xe
    restart: always
    shm_size: 1G
    environment:
      ORACLE_PASSWORD: "password123"
      ORACLE_DATABASE: "oracledb"
    ports:
      - "1521:1521"
      - "8080:8080"
    networks:
      - *network

  # WebTier for load balancing requests to cluster
  webtier:
    image: dockerhub.accenture.com/adop-afpo/oracle-webtier:1221-webtier-apache
    restart: always
    networks:
      - *network 
    environment:
      WEBLOGIC_CLUSTER: "adminserver:8001"
    ports:
      - "80:80"

